### PR TITLE
Add Japanese translations

### PR DESCRIPTION
**Pull request by cognitom**
I'd like to think about the best way to provide translations for the users on this PR.

- `index.md` (Original English document)
- `index.ja.md` (Japanese translation)

Is this make sense? `index.ja-JP.md` is better? (it's the way in react.js)

Any feedback is welcome.

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
I don't know if this makes sense in the official riot repo because you are the only one at moment who could maintain this file, and on any possible router API change this could be a problem. But I would like also to know what @tipiirai thinks about it

**Comment by narikei** [comment]
I also do!
I will support the Japanese translation.

**Comment by srockstyle** [comment]
Nice！ I want to support the Javapanese  translation！

**Comment by tipiirai** [comment]
I think translations should reside on a dedicated *folder*. So `ja/index.md` would be the home page and so on. This would make cuter URLs and linking between the pages. 

Great to see interest on (Japanese) translations!

**Comment by tipiirai** [comment]
OH.... hold on. Just realized that we aren't talking about the website repository :) 

But anyway – I think a separate folder makes more sense here as well.

**Comment by cognitom** [comment]
@narikei @srockstyle I'm happy to hear that :)

@tipiirai Thanks for your feedback. Like this?

```
riot/riot.github.io
- index.md
- guide/
  - router.md <---- riot/router/doc/index.md
- api/
  - router.md <---- riot/router/doc/api.md
- ja/
  - index.md
  - guide/
    - router.md <---- riot/router/doc/ja/index.md
  - api/
    - router.md <---- riot/router/doc/ja/api.md
```

```
riot/router
- doc/
  - index.md
  - api.md
  - ja/
    - index.md
    - api.md
```

**Comment by tipiirai** [comment]
Yes. That makes sense to me.

**Comment by cognitom** [comment]
OK, done. Could you pls merge it? :-)

**Comment by tipiirai** [comment]
Sure. Thanks!

**Pull request merged**
